version: '3.7'

services:
  web:
    container_name: gabestore-frontend
    build:
      context: ./docker/
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 3000:8080
    command: bash -c "npm install && npm run serve"
